import { test, expect } from '@playwright/test';

test('xyz', async ({ page }) => {
  await page.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dyoutube%26oq%3Dyoutube%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDk1MjdqMGoyqAIAsAIB%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3DH3PXafOxBo-s5NoPofCuiQo&q=EgSs0H_3GJ_m3c4GIjAtq-W6OjEDq7IiXlBuKUKFj0jPZJ8VG3wfESoi0QwKAwnAggi4j-BYw16p8zZdMusyAVJaAUM');
  await page.locator('iframe[name="a-vtq7f17j24gk"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="15"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="15"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="15"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="12"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().getByRole('button', { name: 'Skip' }).click();
  await page.locator('iframe[name="c-vtq7f17j24gk"]').contentFrame().getByRole('button', { name: 'Get a new challenge' }).click();
  await page.close();
});
